### ISSUE TITLE
TFAR GUI breaks when using Streamator and TFAR

### ISSUE THREAD

**Issue by Andx667** [TaktiCool/Streamator#17]
### ArmA3 Version:
+ 2.06.148470

### Streamator Version:
+ most recent 

### Mods:
+ https://i.imgur.com/hBigat8.png

### Description:
+TFAR GUI breaks: Input works but the Frequencies are not updated in the GUI, closing and reopen triggers an update but it breaks immediatly again

### Steps to reproduce:
+ Start Game
+ Open any Radio
+ click Channel up -> nothing happens in the display

### Where did the issue occur?
+ Dedicated

### RPT log file:
+ https://pastebin.com/jKRtpN9u (from different Mission with same error)
+ https://pastebin.com/5aUaHTJH (latest mission with this error)

### fix
in https://github.com/TaktiCool/Streamator/blob/7663584289e72ac2ae6f0ad58d31ed6c71d933b5/addons/Streamator/Spectator/TFAR/fn_clientInitTFAR.sqf#L123

replace "call" with "isNil"

**Comment by jokoho48** [comment]
that is a mission builder fault. you should never call any TFAR functions in a Scheduled Environment. and because you do that you trigger an issue. I already had a workaround locally but did not push it. this issue can happen again at any time. with other mods or scripts that use TFAR API or functions.
Fixed in 82c716cf57ad67a3d39e7c3dd228bd482c07eaec
